builds:
  - main: arcd/main.go
    binary: arcd
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm
    hooks:
      pre: ./set_arm_env.sh

archive:
  format: tar.gz
  replacements:
    darwin: macOS
