builds:
  - main: arcd/main.go
    binary: arcd
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd
      - amd64

archive:
  wrap_in_directory: true
  format: tar.gz
  format_overrides:
    - goos: windows
      format: zip
  files:
      - LICENSE
      - README.md
      - arc/**/*

